Repository TheAssemblyArmada/Thyme, pull requests merged in 2022-02, with the labels that each got.

#484 Fix type operator post-increment, shift and unsigned types
  deps/baseconfig/src/typeoperators.h
  deps/baseconfig/src/typesize.h
  src/game/common/system/gametype.h
Labels: bug, fixing

#510 Implement SoundFXNugget
  src/game/client/fxlist.cpp
  src/game/client/fxlist.h
  src/game/common/audio/audioeventrts.h
Labels: engineering

#536 Final bits needed for Drawable
  src/CMakeLists.txt
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/game/client/languagefilter.cpp
  src/game/client/languagefilter.h
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/logic/object/body/bodymodule.h
  src/game/logic/object/contain/opencontain.h
  src/game/logic/object/locomotor.h
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/update/stealthupdate.h
  src/game/logic/object/update/stickybombupdate.h
  src/hooker/setupglobals_zh.cpp
Labels: engineering

#540 Fix some bugs
  src/game/client/draw/w3dmodeldraw.cpp
Labels: bug

#538 Hook PhysicsBehavior::Get_Forward_Speed_2D function
  src/game/common/modules/updatemodule.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#324 Fix compiler signed/unsigned warnings
  src/w3d/renderer/motchan.cpp
  src/w3d/renderer/sortingrenderer.cpp
Labels: fixing

#249 Implements basic SequentialScript.
  src/CMakeLists.txt
  src/game/logic/scriptengine/sequentialscript.cpp
  src/game/logic/scriptengine/sequentialscript.h
Labels: engineering

#248 Implements basic ObjectTypes class.
  src/CMakeLists.txt
  src/game/logic/object/objecttypes.cpp
  src/game/logic/object/objecttypes.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#541 Implement some bits of Drawable
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/game/client/drawgroupinfo.h
  src/game/client/view.h
  src/game/logic/object/object.h
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/client/w3dview.h
Labels: engineering

#543 Implement more of drawable
  src/game/client/anim2d.cpp
  src/game/client/displaystring.h
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/game/client/draw/tintenvelope.cpp
  src/game/client/draw/tintenvelope.h
  src/game/common/audio/audioeventinfo.h
  src/game/common/bitflags.h
  src/game/common/system/xfer.cpp
  src/game/common/system/xfer.h
  src/game/common/thing/thingtemplate.cpp
  src/game/common/thing/thingtemplate.h
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/client/w3dgameclient.cpp
Labels: engineering

#546 Implement more of drawable
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#550 Forces warning 4800 as a error. Fixes cases where it occurs.
  CMakeLists.txt
  src/game/client/display.h
  src/game/common/bitflags.h
  src/game/common/rts/buildinfo.cpp
  src/game/logic/scriptengine/script.cpp
  src/game/logic/scriptengine/scriptgroup.cpp
  src/platform/audio/milesaudiomanager.cpp
  src/platform/w3dengine/client/w3ddisplay.cpp
  src/w3d/renderer/htree.cpp
Labels: fixing

#551 Implement Drawable::Calc_Physics_Xform_Treads
  src/game/client/draw/drawable.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#552 Implement Drawable::Calc_Physics_Xform_Motorcycle
  src/game/client/draw/drawable.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#524 Implement UpdateModule, BehaviorModule
  src/CMakeLists.txt
  src/game/common/bitflags.cpp
  src/game/common/bitflags.h
  src/game/common/modules/behaviormodule.cpp
  src/game/common/modules/behaviormodule.h
  src/game/common/modules/module.cpp
  src/game/common/modules/module.h
  src/game/common/modules/updatemodule.cpp
  src/game/common/modules/updatemodule.h
  src/game/common/system/disabledtypes.cpp
  src/game/common/system/disabledtypes.h
  src/game/common/system/snapshot.h
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/system/gamelogic.cpp
  src/game/logic/system/gamelogic.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#558 Implement more of drawable
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/hooker/setuphooks_zh.cpp
  src/w3d/lib/color.h
Labels: engineering

#563 Final bits of Drawable
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#507 Fix obsolete casts in matrix functions
  src/w3d/math/matrix3.cpp
  src/w3d/math/matrix3d.cpp
  src/w3d/math/matrix3d.h
Labels: refactoring, investigate

#501 Fix some missing float literals in w3d files
  src/game/client/shadow/w3dvolumetricshadow.cpp
  src/game/client/water/w3dwater.cpp
  src/platform/w3dengine/client/w3ddisplay.cpp
  src/platform/w3dengine/client/w3dshroud.cpp
Labels: fixing, investigate

#336 Move Parse_Science_Vector from INI to ScienceStore
  src/game/common/ini/ini.cpp
  src/game/common/ini/ini.h
  src/game/common/rts/playertemplate.cpp
  src/game/common/rts/science.cpp
  src/game/common/rts/science.h
  src/game/logic/system/rankinfo.cpp
Labels: engineering

#503 Force x87 floating point instructions
  CMakeLists.txt
Labels: fixing, investigate

#463 Partially implements GameWindow.
  src/CMakeLists.txt
  src/game/client/gui/gamewindow.cpp
  src/game/client/gui/gamewindow.h
  src/game/client/gui/wininstancedata.cpp
  src/game/client/gui/wininstancedata.h
Labels: engineering

#506 Fix motchan filter table math
  src/w3d/math/gamemath.h
  src/w3d/renderer/motchan.cpp
Labels: fixing, investigate

#485 Change code closer to original in AsciiString and UnicodeString
  src/game/common/system/asciistring.cpp
  src/game/common/system/asciistring.h
  src/game/common/system/unicodestring.cpp
  src/game/common/system/unicodestring.h
Labels: fixing

#508 Add missing float literals and game math functions in some functions
  src/game/client/system/particlesystem/particlesys.cpp
  src/w3d/math/quaternion.cpp
  src/w3d/renderer/assetmgr.cpp
  src/w3d/renderer/camera.cpp
  src/w3d/renderer/dx8wrapper.cpp
Labels: refactoring, investigate

#565 Implement W3DDefaultDraw
  src/CMakeLists.txt
  src/game/client/draw/w3ddefaultdraw.cpp
  src/game/client/draw/w3ddefaultdraw.h
  src/game/client/shadow/w3dshadow.cpp
  src/game/client/shadow/w3dshadow.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#469 Fix ThingTemplate initialization order and missing members
  src/game/common/thing/thingtemplate.cpp
  src/game/common/thing/thingtemplate.h
Labels: vanilla-bug, fixing

#445 Fix motchan types and checks
  src/w3d/renderer/hrawanim.cpp
  src/w3d/renderer/motchan.cpp
  src/w3d/renderer/motchan.h
Labels: fixing

#567 Fix linux compilation issues
  deps/captnlog/CMakeLists.txt
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/client/gametext.cpp
  src/game/client/gui/gamewindow.cpp
  src/game/client/gui/gamewindow.h
  src/game/client/water/w3dwatertracks.cpp
  src/game/client/water/w3dwatertracks.h
  src/game/common/audio/audioeventrts.cpp
  src/game/common/globaldata.cpp
  src/game/common/system/mempoolobj.h
  src/game/common/system/ramfile.cpp
  src/game/common/thing/thing.cpp
  src/game/logic/map/polygontrigger.h
  src/w3d/renderer/dx8caps.cpp
  src/w3d/renderer/dx8vertexbuffer.h
  src/w3d/renderer/mapper.cpp
  src/w3d/renderer/mapper.h
  src/w3d/renderer/w3d.cpp
Labels: fixing

#537 Add placement new operators to IMPLEMENT_NAMED_POOL macro
  src/game/client/anim2d.h
  src/game/client/draw/w3dmodeldraw.h
  src/game/client/image.h
  src/game/client/system/particlesystem/particle.h
  src/game/client/system/particlesystem/particlesys.h
  src/game/common/audio/audioeventinfo.h
  src/game/common/mapobject.h
  src/game/common/statemachine.h
  src/game/common/system/mempoolobj.h
  src/game/logic/object/update/swayclientupdate.h
  src/game/network/gamemessageparser.h
  src/w3d/lib/w3dmpo.h
Labels: refactoring

#568 Fixes up CommandList and GameMessageList.
  src/game/common/commandlist.cpp
  src/game/common/commandlist.h
  src/game/common/gamemessagelist.cpp
Labels: engineering

#569 Implements and partially implements some WND related classes. Fixes issue in FunctionLexicon.
  src/CMakeLists.txt
  src/game/client/gui/windowlayout.cpp
  src/game/client/gui/windowlayout.h
  src/game/common/system/functionlexicon.cpp
Labels: engineering

#570 Implements GameWindowTransitionsHandler layout.
  src/CMakeLists.txt
  src/game/client/gui/gamewindowtransitions.cpp
  src/game/client/gui/gamewindowtransitions.h
Labels: engineering

#571 W3DProjectileStreamDraw and ProjectileStreamUpdate
  src/CMakeLists.txt
  src/game/client/draw/w3dprojectilestreamdraw.cpp
  src/game/client/draw/w3dprojectilestreamdraw.h
  src/game/logic/object/update/projectilestreamupdate.cpp
  src/game/logic/object/update/projectilestreamupdate.h
  src/game/logic/system/gamelogic.cpp
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#247 Pre script engine fixes/implementations.
  src/game/logic/scriptengine/scriptlist.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#576 Implements MissionStats.
  src/CMakeLists.txt
  src/game/common/rts/missionstats.cpp
  src/game/common/rts/missionstats.h
Labels: engineering

#577 W3DTankDraw & W3DOverlordTankDraw
  src/CMakeLists.txt
  src/game/client/draw/w3dmodeldraw.h
  src/game/client/draw/w3doverlordtankdraw.cpp
  src/game/client/draw/w3doverlordtankdraw.h
  src/game/client/draw/w3dtankdraw.cpp
  src/game/client/draw/w3dtankdraw.h
  src/game/client/system/particlesystem/particlesys.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#575 Implements ModalWindow, more of GameWindow.
  src/game/client/gui/gamewindow.cpp
  src/game/client/gui/gamewindow.h
Labels: engineering

#595 Remove C casts in game client code
  src/game/client/gametext.cpp
  src/game/client/worldheightmap.cpp
Labels: refactoring

#593 Remove C casts in common game code
  src/game/common/mapobject.cpp
  src/game/common/overridable.h
  src/game/common/rts/science.cpp
  src/game/common/rts/science.h
Labels: refactoring

#582 Remove C casts in math matrix classes
  src/w3d/math/matrix3.cpp
  src/w3d/math/matrix3.h
  src/w3d/math/matrix3d.cpp
  src/w3d/math/matrix3d.h
  src/w3d/math/matrix4.h
Labels: refactoring

#602 Remove misc C casts
  src/game/client/shadow/w3dprojectedshadow.cpp
  src/game/client/shadow/w3dprojectedshadow.h
  src/game/client/videoplayer/videobuffer.cpp
  src/platform/directx/dinputkeybd.cpp
Labels: refactoring

#600 Remove Vector3 C casts
  src/CMakeLists.txt
  src/w3d/math/tri.h
  src/w3d/math/vector4.cpp
  src/w3d/math/vector4.h
  src/w3d/renderer/meshgeometry.cpp
Labels: refactoring

#596 Remove C casts in w3dwater code
  src/game/client/water/w3dwater.cpp
  src/game/client/water/w3dwatertracks.cpp
Labels: refactoring

#590 Remove C casts in client draw classes
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/game/client/draw/tintenvelope.cpp
  src/game/client/draw/w3ddependencymodeldraw.cpp
  src/game/client/draw/w3ddependencymodeldraw.h
  src/game/client/draw/w3dlaserdraw.h
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/client/draw/w3dmodeldraw.h
  src/game/client/draw/w3dtreedraw.h
Labels: refactoring

#583 Remove C casts and dangerous casts in w3d buffer classes
  src/w3d/lib/buff.cpp
  src/w3d/lib/buff.h
  src/w3d/lib/xstraw.cpp
  src/w3d/lib/xstraw.h
Labels: refactoring

#578 Implement C++17 filesystem
  .github/workflows/linux.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/platform/standardfile.h
  src/platform/stdlocalfilesystem.cpp
  src/platform/stdlocalfilesystem.h
  src/platform/win32gameengine.cpp
  src/platform/win32localfile.h
Labels: enhancement

#611 Fix ini constness
  src/game/client/anim2d.cpp
  src/game/client/anim2d.h
  src/game/client/draw/w3ddependencymodeldraw.cpp
  src/game/client/draw/w3dlaserdraw.cpp
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/client/draw/w3doverlordtankdraw.cpp
  src/game/client/draw/w3dprojectilestreamdraw.cpp
  src/game/client/draw/w3dtankdraw.cpp
  src/game/client/draw/w3dtreedraw.cpp
  src/game/client/drawgroupinfo.cpp
  src/game/client/drawgroupinfo.h
  src/game/client/fxlist.cpp
  src/game/client/globallanguage.cpp
  src/game/client/globallanguage.h
  src/game/client/image.cpp
  src/game/client/image.h
  src/game/client/input/mouse.cpp
  src/game/client/system/particlesystem/particlesystemplate.cpp
  src/game/client/system/particlesystem/particlesystemplate.h
  src/game/client/terrainroads.cpp
  src/game/client/terrainroads.h
  src/game/client/videoplayer/videoplayer.cpp
  src/game/client/videoplayer/videoplayer.h
  src/game/client/water.cpp
  src/game/client/water.h
  src/game/common/audio/audioeventinfo.cpp
  src/game/common/audio/audioeventinfo.h
  src/game/common/audio/audiomisc.cpp
  src/game/common/audio/audiomisc.h
  src/game/common/audio/audiosettings.cpp
  src/game/common/audio/audiosettings.h
  src/game/common/gamelod.cpp
  src/game/common/globaldata.cpp
  src/game/common/globaldata.h
  src/game/common/ini/ini.cpp
  src/game/common/ini/ini.h
  src/game/common/multiplayersettings.cpp
  src/game/common/multiplayersettings.h
  src/game/common/rts/playertemplate.cpp
  src/game/common/rts/science.cpp
  src/game/common/rts/science.h
  src/game/common/terraintypes.cpp
  src/game/common/terraintypes.h
  src/game/common/thing/thingtemplate.cpp
  src/game/common/thing/thingtemplate.h
  src/game/logic/object/armortemplateset.cpp
  src/game/logic/object/objectcreationlist.cpp
  src/game/logic/object/update/laserupdate.cpp
  src/game/logic/object/weapontemplateset.cpp
  src/game/logic/system/rankinfo.cpp
  src/game/weather.cpp
  src/game/weather.h
Labels: refactoring

#605 W3DTankTruckDraw
  src/CMakeLists.txt
  src/game/client/draw/w3dtankdraw.cpp
  src/game/client/draw/w3dtanktruckdraw.cpp
  src/game/client/draw/w3dtanktruckdraw.h
  src/game/client/system/particlesystem/particlesys.h
  src/game/common/thing/thingtemplate.cpp
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#612 Partially implements IMEManager.
  src/CMakeLists.txt
  src/game/client/gui/imemanager.cpp
  src/game/client/gui/imemanager.h
  src/game/client/gui/imemanagerinterface.cpp
  src/game/client/gui/imemanagerinterface.h
  src/hooker/setupglobals_zh.cpp
Labels: engineering

#359 ScienceStore
  src/game/common/ini/ini.cpp
  src/game/common/rts/science.cpp
  src/game/common/rts/science.h
  src/game/common/thing/thingtemplate.h
  src/hooker/setuphooks_wb.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#615 Fixes various audio enums, fixes some issues in audio code.
  src/game/common/audio/audioeventinfo.h
  src/game/common/audio/audioeventrts.cpp
  src/game/common/audio/audioeventrts.h
  src/game/common/audio/audiomanager.cpp
  src/game/common/audio/audiomanager.h
  src/game/common/audio/audiorequest.h
  src/game/common/audio/musicmanager.cpp
  src/game/common/audio/soundmanager.cpp
  src/platform/audio/milesaudiomanager.cpp
  src/platform/audio/milesaudiomanager.h
  src/platform/audio/playingaudio.h
Labels: fixing

#603 Fix issues in FontCharsClass::Create_GDI_Font
  src/w3d/renderer/render2dsentence.cpp
Labels: fixing

#589 Remove C casts from INI parse functions
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/common/bitflags.h
  src/game/common/gamelod.cpp
  src/game/common/thing/thingtemplate.cpp
Labels: refactoring

#613 WndProc
  src/game/client/gui/imemanager.cpp
  src/game/client/gui/imemanager.h
  src/game/client/gui/imemanagerinterface.h
  src/game/main.cpp
  src/game/main.h
  src/hooker/setupglobals_zh.cpp
  src/platform/input/win32mouse.h
Labels: engineering

#623 Simplify minor code around ThingTemplate class
  src/game/common/rts/productionprerequisite.cpp
  src/game/common/thing/thingtemplate.cpp
  src/game/logic/ai/aipathfind.h
Labels: refactoring

#598 Remove C casts in w3d renderer code
  src/w3d/renderer/animobj.cpp
  src/w3d/renderer/animobj.h
  src/w3d/renderer/dx8wrapper.cpp
  src/w3d/renderer/meshmatdesc.cpp
  src/w3d/renderer/rendobj.cpp
Labels: refactoring

#610 Add natvis for stl port vector
  CMakeLists.txt
  resources/visualstudio/stllist.natvis
  resources/visualstudio/stlvector.natvis
Labels: enhancement

#580 Remove several C casts in renderer code
  src/w3d/renderer/dx8indexbuffer.cpp
  src/w3d/renderer/dx8renderer.cpp
  src/w3d/renderer/dx8renderer.h
  src/w3d/renderer/dx8vertexbuffer.cpp
  src/w3d/renderer/dx8wrapper.cpp
  src/w3d/renderer/dx8wrapper.h
  src/w3d/renderer/mapper.cpp
  src/w3d/renderer/textureloader.cpp
  src/w3d/renderer/textureloadtask.cpp
  src/w3d/renderer/thumbnail.cpp
  src/w3d/renderer/vertmaterial.cpp
Labels: refactoring

#587 Remove C casts from FieldParse tables
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/client/drawgroupinfo.cpp
  src/game/common/thing/thingtemplate.cpp
Labels: refactoring

#562 Implements ScoreKeeper.
  src/CMakeLists.txt
  src/game/common/rts/scorekeeper.cpp
  src/game/common/rts/scorekeeper.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#559 Put Player function declarations and class members
  src/game/client/shadow/w3dvolumetricshadow.h
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/common/rts/scorekeeper.h
  src/game/common/system/asciistring.cpp
  src/game/common/system/unicodestring.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#653 Check return value of sscanf for commandline parse to avoid using gar…
  src/game/common/commandline.cpp
Labels: bug, fixing

#632 Fix non zero constant expression in main function
  src/game/main.cpp
Labels: bug, fixing

#616 Fix undefined behavior in INI::Scan_IndexList
  src/game/common/audio/audioeventinfo.cpp
  src/game/common/gamelod.cpp
  src/game/common/ini/ini.cpp
  src/game/common/ini/ini.h
Labels: bug, fixing

#643 Protect from null pointer access in RTS3DScene constructor
  src/platform/w3dengine/client/w3dscene.cpp
Labels: bug, fixing

#639 Fix use of wrong position in W3DModelDraw::Get_Projectile_Launch_Offset
  src/game/client/draw/w3dmodeldraw.cpp
Labels: bug, fixing

#651 Initialize additional variables in platform code
  src/platform/video/binkvideostream.h
  src/platform/w3dfilesystem.cpp
Labels: fixing

#641 Avoid invalid indexing in GameLODManager::Get_Recommended_Texture_Red…
  src/game/common/gamelod.cpp
Labels: fixing

#637 Avoid crash if texture passed to GameAssetManager::Recolor_Texture_On…
  src/w3d/renderer/assetmgr.cpp
Labels: fixing

#652 Initialize additional variables in game code
  src/game/logic/object/update/projectilestreamupdate.cpp
  src/game/logic/system/rankinfo.h
  src/game/network/udp.h
Labels: fixing

#633 Fix potential nullptr access in SurfaceClass::Is_Transparent_Column
  src/w3d/renderer/surfaceclass.cpp
Labels: bug, refactoring, fixing

#646 Initialize additional variables in game client code
  src/game/client/draw/drawable.cpp
  src/game/client/draw/drawable.h
  src/game/client/gui/gamefont.h
  src/game/client/shader/maskshader.cpp
  src/game/client/shader/motionblurfilter.cpp
  src/game/client/shadow/w3dshadow.h
  src/game/client/water/w3dwatertracks.cpp
Labels: fixing

#647 Initialize additional class members in w3dengine code
  src/platform/w3dengine/client/w3ddisplay.cpp
  src/platform/w3dengine/client/w3ddynamiclight.h
  src/platform/w3dengine/client/w3droadbuffer.cpp
  src/platform/w3dengine/client/w3dscene.cpp
  src/platform/w3dengine/client/w3dsmudge.h
Labels: fixing

#649 Initialize additional variables in w3d code
  src/w3d/lib/cpudetect.cpp
  src/w3d/lib/hash.h
  src/w3d/lib/thread.cpp
  src/w3d/math/colmathaabtri.cpp
Labels: fixing

#648 Initialize additional class members in w3d renderer code
  src/w3d/renderer/assetmgr.h
  src/w3d/renderer/coltest.h
  src/w3d/renderer/ddsfile.cpp
  src/w3d/renderer/dx8wrapper.h
  src/w3d/renderer/htree.cpp
  src/w3d/renderer/matinfo.cpp
  src/w3d/renderer/meshmdl.cpp
  src/w3d/renderer/proto.h
  src/w3d/renderer/renderdevicedesc.h
  src/w3d/renderer/scene.h
  src/w3d/renderer/seglinerenderer.cpp
Labels: fixing

#640 Initialize all pointers in WriteLockClass classes
  src/w3d/renderer/dx8indexbuffer.cpp
  src/w3d/renderer/dx8vertexbuffer.cpp
Labels: fixing

#644 Initialize additional class members in particle code
  src/game/client/system/particlesystem/particleinfo.cpp
  src/game/client/system/particlesystem/particlesysinfo.cpp
Labels: fixing

#635 Compare HRESULT against D3D_OK
  src/game/client/shadow/w3dprojectedshadow.cpp
  src/game/client/water/w3dwater.cpp
  src/game/client/water/w3dwatertracks.cpp
Labels: refactoring

#655 Fix crash in Drawable::Is_Visible
  src/game/client/draw/drawable.cpp
Labels: bug, fixing

#656 Use FAILED and SUCCEEDED macros instead of D3D_OK value
  src/game/client/shadermanager.cpp
  src/game/client/shadow/w3dprojectedshadow.cpp
  src/game/client/water/w3dwater.cpp
  src/game/client/water/w3dwatertracks.cpp
  src/platform/w3dengine/client/w3ddisplay.cpp
  src/platform/w3dengine/client/w3dshroud.cpp
  src/w3d/renderer/dx8wrapper.cpp
  src/w3d/renderer/dx8wrapper.h
  src/w3d/renderer/w3d.cpp
Labels: refactoring

#594 Remove C casts in w3dengine code
  src/platform/w3dengine/client/w3dbridgebuffer.cpp
  src/platform/w3dengine/client/w3ddisplay.cpp
  src/platform/w3dengine/client/w3droadbuffer.cpp
  src/platform/w3dengine/client/w3dscene.cpp
  src/platform/w3dengine/client/w3dshroud.cpp
  src/platform/w3dengine/client/w3dsmudge.cpp
Labels: refactoring

#477 Guard hooker.h with compile error if used in non GAME_DLL
  src/hooker/hooker.h
Labels: fixing, investigate

#584 Remove some C casts in w3d lib code
  src/w3d/lib/iniclass.cpp
  src/w3d/lib/multilist.h
  src/w3d/lib/random.cpp
  src/w3d/lib/wwstring.h
  src/w3d/math/tri.h
Labels: refactoring

#642 Initialize additional class members in audio code
  src/game/common/audio/audioeventinfo.cpp
  src/game/common/audio/audioeventinfo.h
  src/game/common/audio/audioeventrts.cpp
  src/game/common/audio/audiorequest.h
  src/game/common/audio/audiosettings.cpp
  src/game/common/audio/audiosettings.h
  src/game/common/audio/soundmanager.h
Labels: fixing
