Repository TheAssemblyArmada/Thyme, pull requests merged in 2022-09, with the labels that each got.

#722 Import wdump clone from TT scripts
  .github/workflows/windows.yml
  resources/wdump/resource.h
  resources/wdump/wdump.ico
  resources/wdump/wdump.rc
  src/tools/CMakeLists.txt
  src/tools/wdump/CMakeLists.txt
  src/tools/wdump/wdump.cpp
  src/w3d/renderer/meshgeometry.cpp
  src/w3d/renderer/w3d_file.h
  src/w3d/renderer/w3d_obsolete.h
Labels: engineering

#731 Alters how wxWidgets dependency is handled.
  CMakeLists.txt
Labels: fixing

#744 Fix idle animation issue
  src/game/client/draw/w3dmodeldraw.cpp
Labels: bug, fixing
