Repository TheAssemblyArmada/Thyme, pull requests merged in 2022-10, with the labels that each got.

#726 Cleanup RenderObjClass properly
  src/w3d/renderer/rendobj.cpp
  src/w3d/renderer/rendobj.h
Labels: fixing

#597 Simplify code in Create_Bmp_File function
  src/platform/w3dengine/client/w3ddisplay.cpp
Labels: fixing

#601 Remove Matrix4 C casts
  src/game/client/shader/cloudshader.cpp
  src/game/client/shader/flatshroudshader.cpp
  src/game/client/shader/flatterrainshader.cpp
  src/game/client/shader/maskshader.cpp
  src/game/client/shader/roadshader.cpp
  src/game/client/shader/shroudshader.cpp
  src/game/client/shader/terrainshader.cpp
  src/game/client/shadermanager.cpp
  src/game/client/shadow/w3dprojectedshadow.cpp
  src/game/client/water/w3dwater.cpp
  src/game/common/beziersegment.cpp
  src/hooker/setupglobals_zh.cpp
  src/w3d/math/matrix4.cpp
  src/w3d/math/matrix4.h
  src/w3d/renderer/dx8renderer.cpp
  src/w3d/renderer/dx8wrapper.cpp
  src/w3d/renderer/dx8wrapper.h
  src/w3d/renderer/sortingrenderer.cpp
Labels: refactoring, fixing

#748 Fixes broken game message chain handling.
  src/game/common/messagestream.cpp
Labels: fixing

#667 Print assert message on assert log
  deps/captnlog/src/captainslog.h
  deps/captnlog/src/captnlog.c
Labels: enhancement

#753 Implement more of Locomotor
  src/game/logic/object/locomotor.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#754 Implement more of locomotor
  src/game/logic/object/locomotor.cpp
  src/game/logic/object/locomotor.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#585 Remove C casts in RankInfo class
  src/game/logic/system/rankinfo.cpp
  src/game/logic/system/rankinfo.h
Labels: refactoring

#756 PhysicsBehavior bits
  src/CMakeLists.txt
  src/game/client/draw/drawable.cpp
  src/game/client/draw/w3dtruckdraw.cpp
  src/game/common/modules/behaviormodule.h
  src/game/logic/object/locomotor.cpp
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/update/physicsupdate.cpp
  src/game/logic/object/update/physicsupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/object/weapon.h
  src/game/logic/system/damage.cpp
  src/game/logic/system/damage.h
  src/hooker/setupglobals_zh.cpp
Labels: engineering

#758 PhysicsBehavior
  src/game/common/audio/audiomanager.cpp
  src/game/common/audio/audiomanager.h
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/object/update/physicsupdate.cpp
  src/game/logic/object/update/physicsupdate.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#761 Implement stuff needed for TurretAI
  src/CMakeLists.txt
  src/game/common/statemachine.cpp
  src/game/common/statemachine.h
  src/game/logic/ai/aistates.cpp
  src/game/logic/ai/aistates.h
  src/game/logic/ai/turretai.cpp
  src/game/logic/ai/turretai.h
  src/game/logic/map/terrainlogic.cpp
  src/game/logic/map/terrainlogic.h
  src/game/logic/object/object.cpp
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/object/weapon.h
  src/game/logic/object/weaponset.h
Labels: engineering

#762 TurretAI
  src/game/common/modules/updatemodule.h
  src/game/common/statemachine.h
  src/game/common/system/gametype.h
  src/game/logic/ai/aistates.cpp
  src/game/logic/ai/aistates.h
  src/game/logic/ai/turretai.cpp
  src/game/logic/ai/turretai.h
  src/game/logic/object/object.h
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/object/weapon.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#765 W3DRopeDraw
  src/CMakeLists.txt
  src/game/client/draw/w3dropedraw.cpp
  src/game/client/draw/w3dropedraw.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#769 W3DPropDraw, W3DDebrisDraw and W3DTracerDraw
  src/CMakeLists.txt
  src/game/client/baseheightmap.cpp
  src/game/client/baseheightmap.h
  src/game/client/draw/drawable.h
  src/game/client/draw/w3ddebrisdraw.cpp
  src/game/client/draw/w3ddebrisdraw.h
  src/game/client/draw/w3dpropdraw.cpp
  src/game/client/draw/w3dpropdraw.h
  src/game/client/draw/w3dtracerdraw.cpp
  src/game/client/draw/w3dtracerdraw.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#772 Refactor variable names in W3DRopeDraw
  src/game/client/draw/w3dropedraw.cpp
  src/game/client/draw/w3dropedraw.h
Labels: refactoring

#775 Remove public mutable string functions in Utf8String and Utf16String
  src/game/common/system/archivefile.cpp
  src/game/common/system/asciistring.cpp
  src/game/common/system/asciistring.h
  src/game/common/system/datachunk.cpp
  src/game/common/system/datachunktoc.cpp
  src/game/common/system/unicodestring.cpp
  src/game/common/system/unicodestring.h
  src/game/network/lanapi.cpp
  src/game/network/lanapi.h
Labels: bug, fixing

#771 Refactor AnimationStateFlag handling
  src/game/client/draw/w3dmodeldraw.cpp
Labels: refactoring

#592 Remove C casts in logic object code
  src/game/common/thing/thingtemplate.cpp
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/object/update/laserupdate.h
Labels: refactoring

#773 Implement DLINK_ITERATOR, TeamRelationMap, TeamFactory, TeamTemplateInfo, bits of Team and bits of TeamPrototype
  src/CMakeLists.txt
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/common/rts/team.cpp
  src/game/common/rts/team.h
  src/game/common/staticnamekey.cpp
  src/game/common/staticnamekey.h
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/scriptengine/scriptengine.cpp
  src/game/logic/scriptengine/scriptengine.h
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering
