Repository TheAssemblyArmada/Thyme, pull requests merged in 2022-03, with the labels that each got.

#622 Add googletest for testing & add filesystem test suite
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  src/platform/standardfile.h
  src/platform/stdlocalfilesystem.cpp
  src/platform/stdlocalfilesystem.h
  src/platform/win32gameengine.cpp
  src/platform/win32localfile.h
  src/platform/win32localfilesystem.cpp
  src/w3d/lib/cpudetect.cpp
  tests/CMakeLists.txt
  tests/data/test.big
  tests/data/test.ini
  tests/globals.cpp
  tests/test_filesystem.cpp
Labels: enhancement

#581 Replace C casts with union in Vector2i and Vector3i
  src/w3d/math/vector2i.h
  src/w3d/math/vector3i.h
Labels: refactoring

#634 Add missing breaks in several switch cases
  src/platform/audio/milesaudiomanager.cpp
  src/w3d/lib/cpudetect.cpp
  src/w3d/renderer/dx8wrapper.cpp
  src/w3d/renderer/meshmatdesc.h
  src/w3d/renderer/meshmdl.cpp
Labels: bug, fixing

#672 Fix constness in MilesAudioFileCache::Open_File function
  src/game/common/audio/audioeventrts.cpp
  src/game/common/audio/audioeventrts.h
  src/platform/audio/milesaudiofilecache.cpp
  src/platform/audio/milesaudiofilecache.h
Labels: refactoring

#663 Finish the last functions for ProductionPrerequisite, ThingTemplate and ThingFactory.
  src/game/common/modules/behaviormodule.h
  src/game/common/rts/handicap.cpp
  src/game/common/rts/handicap.h
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/common/rts/productionprerequisite.cpp
  src/game/common/rts/productionprerequisite.h
  src/game/common/thing/thingfactory.cpp
  src/game/common/thing/thingtemplate.cpp
  src/game/common/thing/thingtemplate.h
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/system/gamelogic.cpp
  src/game/logic/system/gamelogic.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#677 Demote data assert to log message in ThingFactory::New_Object
  src/game/common/thing/thingfactory.cpp
Labels: vanilla-bug, fixing

#674 W3DOverlordAircraftDraw
  src/CMakeLists.txt
  src/game/client/draw/w3doverlordaircraftdraw.cpp
  src/game/client/draw/w3doverlordaircraftdraw.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#682 Simplify Array Hooking
  src/game/client/water.h
  src/hooker/hooker.h
  src/hooker/setupglobals_zh.cpp
Labels: refactoring

#347 Improve game hooking lifetime and technique
  src/CMakeLists.txt
  src/hooker/dllmain.cpp
  src/hooker/hooker.cpp
  src/hooker/hooker.h
  src/hooker/mapview.cpp
  src/hooker/mapview.h
Labels: enhancement, investigate

#588 Match reference counter type in String classes with Windows interlock…
  src/game/common/system/asciistring.h
  src/game/common/system/unicodestring.cpp
  src/game/common/system/unicodestring.h
Labels: fixing

#591 Fix malicious invocations of SetPixelShaderConstant
  src/game/client/shader/bwfilter.cpp
  src/game/client/water/w3dwater.cpp
Labels: refactoring

#664 Fix unsafe Game String copy overlap
  src/game/common/system/asciistring.cpp
  src/game/common/system/unicodestring.cpp
  src/game/common/system/unicodestring.h
Labels: fixing

#687 Fix W3D Overlord tint crash
  src/game/client/draw/w3doverlordaircraftdraw.cpp
  src/game/client/draw/w3doverlordtankdraw.cpp
  src/game/client/draw/w3doverlordtruckdraw.cpp
Labels: bug, fixing

#678 Fixes audio volume regression.
  src/game/common/audio/audiomanager.cpp
  src/platform/audio/milesaudiomanager.cpp
Labels: bug, fixing

#645 Fix bug in Drawable::Set_Stealth_Look
  src/game/client/draw/drawable.cpp
Labels: bug, fixing

#668 Demote asserts to log errors in W3DTruckDraw::Update_Bones
  src/game/client/draw/w3dtruckdraw.cpp
Labels: vanilla-bug, fixing

#669 Remove log spam and reinstate disabled asserts as error log messages
  src/game/client/draw/drawable.cpp
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/common/thing/thingfactory.cpp
Labels: vanilla-bug, fixing

#685 Refactor static name key names and constness
  src/game/client/draw/drawable.cpp
  src/game/client/draw/w3ddefaultdraw.cpp
  src/game/client/draw/w3ddependencymodeldraw.cpp
  src/game/client/draw/w3dlaserdraw.cpp
  src/game/client/draw/w3dmodeldraw.cpp
  src/game/client/draw/w3doverlordaircraftdraw.cpp
  src/game/client/draw/w3doverlordtankdraw.cpp
  src/game/client/draw/w3doverlordtruckdraw.cpp
  src/game/client/draw/w3dpolicecardraw.cpp
  src/game/client/draw/w3dprojectilestreamdraw.cpp
  src/game/client/draw/w3dtankdraw.cpp
  src/game/client/draw/w3dtanktruckdraw.cpp
  src/game/client/draw/w3dtreedraw.cpp
  src/game/client/draw/w3dtruckdraw.cpp
  src/game/logic/object/update/laserupdate.cpp
  src/game/logic/object/update/projectilestreamupdate.cpp
  src/game/logic/object/update/swayclientupdate.cpp
Labels: refactoring

#686 Add CRC tests
  tests/CMakeLists.txt
  tests/test_crc.cpp
Labels: enhancement

#680 W3DScienceModelDraw
  src/CMakeLists.txt
  src/game/client/draw/w3dsciencemodeldraw.cpp
  src/game/client/draw/w3dsciencemodeldraw.h
  src/game/common/rts/player.h
  src/game/common/rts/science.cpp
  src/game/common/rts/science.h
  src/platform/w3dengine/common/thing/w3dmodulefactory.cpp
Labels: engineering

#684 Implements crude ShaderClass::Apply.
  src/w3d/renderer/dx8caps.h
  src/w3d/renderer/dx8wrapper.h
  src/w3d/renderer/shader.cpp
Labels: engineering

#691 Implement DynamicMeshClass, DynamicMeshModel and Bitmap2D
  src/CMakeLists.txt
  src/w3d/lib/w3dmpo.h
  src/w3d/renderer/bmp2d.cpp
  src/w3d/renderer/bmp2d.h
  src/w3d/renderer/boxrobj.h
  src/w3d/renderer/dynamesh.cpp
  src/w3d/renderer/dynamesh.h
  src/w3d/renderer/render2dsentence.h
  src/w3d/renderer/texture.h
  src/w3d/renderer/texturebase.h
Labels: engineering

#693 PointGroupClass
  src/hooker/setuphooks_zh.cpp
  src/w3d/renderer/pointgr.cpp
  src/w3d/renderer/pointgr.h
Labels: engineering

#619 Work on FFmpeg audio cache
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  cmake/modules/FindFFmpeg.cmake
  src/CMakeLists.txt
  src/platform/audio/ffmpegaudiofilecache.cpp
  src/platform/audio/ffmpegaudiofilecache.h
  src/platform/audio/milesaudiomanager.cpp
  src/platform/audio/milesaudiomanager.h
  tests/CMakeLists.txt
  tests/data/audio/ima44s.wav
  tests/data/audio/pcm1644m.wav
  tests/data/filesystem/test.big
  tests/data/filesystem/test.ini
  tests/main.cpp
  tests/test_audiofilecache.cpp
  tests/test_filesystem.cpp
Labels: enhancement

#706 Fixes wrong member type in W3DMaskMaterialPassClass.
  src/platform/w3dengine/client/w3dshroud.h
Labels: fixing
