Repository TheAssemblyArmada/Thyme, pull requests merged in 2023-01, with the labels that each got.

#818 Implement some of Weapon
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/common/rts/team.cpp
  src/game/common/rts/team.h
  src/game/logic/object/object.cpp
  src/game/logic/object/update/projectilestreamupdate.cpp
  src/game/logic/object/update/projectilestreamupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/object/weapon.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#794 Fix invalidated iterator dereference in ScienceStore, LocomotorStore, RankInfoStore
  src/game/common/rts/science.cpp
  src/game/logic/object/locomotor.cpp
  src/game/logic/system/rankinfo.cpp
Labels: vanilla-bug, fixing

#822 Final bits of weapon code
  src/CMakeLists.txt
  src/game/common/modules/behaviormodule.h
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/logic/ai/aipathfind.cpp
  src/game/logic/ai/aipathfind.h
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/update/assistedtargetingupdate.cpp
  src/game/logic/object/update/assistedtargetingupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/object/weapon.h
  src/game/logic/object/weaponset.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#829 Finish the implementation of MultiplayerColorDefinition and MultiplayerSettings
  src/game/common/gameengine.cpp
  src/game/common/ini/ini.cpp
  src/game/common/multiplayersettings.cpp
  src/game/common/multiplayersettings.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering, fixing

#833 Implement more of GameEngine::Init
  src/CMakeLists.txt
  src/game/common/gameengine.cpp
  src/game/common/system/buildassistant.cpp
  src/game/common/system/buildassistant.h
  src/game/common/system/upgrade.cpp
  src/game/common/system/upgrade.h
  src/game/logic/ai/ai.cpp
  src/game/logic/ai/ai.h
  src/game/logic/ai/aipathfind.cpp
  src/game/logic/ai/aipathfind.h
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering
