Repository TheAssemblyArmada/Thyme, pull requests merged in 2023-05, with the labels that each got.

#909 Implement some stuff needed for AIGroup
  src/CMakeLists.txt
  src/game/client/line2d.cpp
  src/game/client/line2d.h
  src/game/common/rts/actionmanager.cpp
  src/game/common/rts/actionmanager.h
  src/game/common/rts/specialpower.cpp
  src/game/common/rts/specialpower.h
  src/game/common/system/upgrade.cpp
  src/game/common/system/upgrade.h
  src/game/logic/ai/ai.cpp
  src/game/logic/ai/ai.h
  src/game/logic/ai/aigroup.cpp
  src/game/logic/ai/aigroup.h
  src/game/logic/ai/aipathfind.cpp
  src/game/logic/ai/aipathfind.h
  src/game/logic/object/locomotor.cpp
  src/game/logic/object/object.cpp
  src/game/logic/object/object.h
  src/game/logic/object/update/aiupdate.cpp
  src/game/logic/object/update/aiupdate.h
  src/game/logic/object/update/stealthupdate.h
  src/game/logic/object/weapon.cpp
  src/game/logic/system/simpleobjectiterator.cpp
  src/game/logic/system/simpleobjectiterator.h
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#910 Implement AIGroup
  src/game/common/system/buildassistant.h
  src/game/logic/ai/ai.cpp
  src/game/logic/ai/ai.h
  src/game/logic/ai/aigroup.cpp
  src/game/logic/ai/aigroup.h
  src/game/logic/ai/aipathfind.cpp
  src/game/logic/ai/aipathfind.h
  src/game/logic/object/locomotor.h
  src/game/logic/object/object.h
  src/game/logic/system/simpleobjectiterator.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#918 Improves readability in BaseHeightMapRenderObjClass::Is_Clear_Line_Of…
  src/game/client/baseheightmap.cpp
Labels: refactoring

#923 Cleanup and finish the definition of various script related classes
  src/game/client/worldheightmap.cpp
  src/game/common/rts/buildinfo.cpp
  src/game/common/rts/buildinfo.h
  src/game/common/rts/player.cpp
  src/game/common/rts/player.h
  src/game/common/rts/playerlist.cpp
  src/game/common/rts/sidesinfo.cpp
  src/game/common/rts/sidesinfo.h
  src/game/common/rts/sideslist.cpp
  src/game/common/rts/sideslist.h
  src/game/common/rts/team.cpp
  src/game/common/rts/team.h
  src/game/common/rts/teamsinfo.cpp
  src/game/common/rts/teamsinfo.h
  src/game/logic/scriptengine/script.cpp
  src/game/logic/scriptengine/script.h
  src/game/logic/scriptengine/scriptaction.cpp
  src/game/logic/scriptengine/scriptaction.h
  src/game/logic/scriptengine/scriptcondition.cpp
  src/game/logic/scriptengine/scriptcondition.h
  src/game/logic/scriptengine/scriptengine.h
  src/game/logic/scriptengine/scriptgroup.cpp
  src/game/logic/scriptengine/scriptgroup.h
  src/game/logic/scriptengine/scriptlist.cpp
  src/game/logic/scriptengine/scriptlist.h
  src/game/logic/scriptengine/scriptparam.cpp
  src/game/logic/scriptengine/scriptparam.h
  src/game/logic/scriptengine/scripttemplate.h
  src/hooker/setuphooks_zh.cpp
Labels: refactoring, engineering, fixing

#920 Add Is_Nan function to build with/without gamemath enabled
  src/game/common/thing/thing.cpp
  src/game/logic/object/object.cpp
  src/game/logic/object/update/physicsupdate.cpp
  src/w3d/math/gamemath.h
Labels: fixing
