Repository TheAssemblyArmada/Thyme, pull requests merged in 2024-02, with the labels that each got.

#1065 Implement more of InGameUI
  src/game/client/ingameui.cpp
  src/game/client/ingameui.h
  src/game/common/rts/actionmanager.cpp
  src/game/common/rts/actionmanager.h
  src/game/common/rts/player.cpp
  src/game/logic/ai/aigroup.cpp
  src/game/logic/ai/turretai.cpp
  src/game/logic/object/weaponset.cpp
  src/game/logic/object/weaponset.h
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/client/w3dgameclient.cpp
  src/platform/w3dengine/client/w3dingameui.cpp
  src/platform/w3dengine/client/w3dingameui.h
Labels: engineering

#1080 Implement more GameClient stuff
  src/game/client/eva.cpp
  src/game/client/eva.h
  src/game/client/gameclient.cpp
  src/game/client/gui/headertemplate.cpp
  src/game/client/gui/headertemplate.h
  src/game/client/gui/imemanager.cpp
  src/game/client/gui/imemanager.h
  src/game/client/gui/shell/shell.h
  src/game/client/gui/shell/shellmenuscheme.cpp
  src/game/client/gui/shell/shellmenuscheme.h
  src/game/client/ingameui.cpp
  src/game/client/system/campaignmanager.cpp
  src/game/client/system/campaignmanager.h
  src/game/client/system/particlesystem/particlesys.cpp
  src/game/client/videoplayer/videoplayer.cpp
  src/game/client/videoplayer/videoplayer.h
  src/game/common/ini/ini.cpp
  src/game/logic/object/objectcreationlist.cpp
  src/game/logic/object/objectcreationlist.h
  src/game/logic/object/partitionmanager.cpp
  src/game/logic/object/partitionmanager.h
  src/game/logic/object/update/laserupdate.cpp
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/client/w3dpropbuffer.cpp
  src/platform/w3dengine/client/w3dscene.cpp
  src/platform/w3dengine/client/w3dtreebuffer.cpp
  src/platform/w3dengine/client/w3dview.cpp
  src/platform/w3dengine/logic/w3dghostobject.cpp
Labels: engineering

#802 Fix CI warnings
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: fixing

#1085 Implement some INI parsing stuff
  src/CMakeLists.txt
  src/game/client/credits.cpp
  src/game/client/credits.h
  src/game/client/globallanguage.h
  src/game/common/ini/ini.cpp
  src/game/common/ini/ini.h
  src/game/common/rts/buildinfo.cpp
  src/game/common/rts/buildinfo.h
  src/game/common/system/gametype.h
  src/game/logic/ai/ai.cpp
  src/game/logic/ai/ai.h
  src/game/logic/ai/aipathfind.cpp
  src/game/logic/ai/aipathfind.h
  src/game/logic/system/cratesystem.cpp
  src/game/logic/system/cratesystem.h
  src/hooker/setupglobals_zh.cpp
  src/hooker/setuphooks_zh.cpp
  src/platform/w3dengine/common/win32gameengine.cpp
Labels: engineering

#1088 Implement more INI stuff
  src/game/client/maputil.cpp
  src/game/client/maputil.h
  src/game/client/messagestream/metaevent.cpp
  src/game/client/messagestream/metaevent.h
  src/game/client/system/particlesystem/particlesysmanager.cpp
  src/game/client/system/particlesystem/particlesysmanager.h
  src/game/common/damagefx.cpp
  src/game/common/damagefx.h
  src/game/common/ini/ini.cpp
  src/game/common/ini/ini.h
  src/game/common/system/quotedprintable.cpp
  src/game/common/system/quotedprintable.h
  src/game/logic/object/armor.cpp
  src/game/logic/object/armor.h
  src/game/logic/object/armortemplateset.cpp
  src/game/logic/object/objectcreationlist.cpp
  src/game/logic/object/objectcreationlist.h
Labels: engineering

#1089 Implement more UI code
  src/game/client/gui/gadget/gadgetcheckbox.cpp
  src/game/client/gui/gadget/gadgetcheckbox.h
  src/game/client/gui/gadget/gadgetcombobox.cpp
  src/game/client/gui/gadget/gadgetcombobox.h
  src/game/client/gui/gadget/gadgetlistbox.cpp
  src/game/client/gui/gadget/gadgetpushbutton.cpp
  src/game/client/gui/gadget/gadgetpushbutton.h
  src/game/client/gui/gadget/gadgetradiobutton.cpp
  src/game/client/gui/gadget/gadgetradiobutton.h
  src/game/client/gui/gadget/gadgettabcontrol.cpp
  src/game/client/gui/gadget/gadgettabcontrol.h
  src/game/client/gui/gadget/gadgettextentry.cpp
  src/game/client/gui/gadget/gadgettextentry.h
  src/game/common/system/unicodestring.cpp
  src/hooker/setuphooks_zh.cpp
Labels: engineering

#788 Reduce file string allocations
  src/game/common/system/file.cpp
  src/game/common/system/file.h
Labels: optimization

#786 Fix file function constness
  src/game/common/system/file.h
Labels: vanilla-bug, fixing

#917 Improves readability in BaseHeightMapRenderObjClass::Get_Height_Map_Height
  src/platform/w3dengine/client/baseheightmap.cpp
Labels: refactoring

#1116 Avoid stlport compile error with Visual Studio 2022
  deps/stlport/exception
Labels: fixing

#1117 Fix vs2022 clang format
  .clang-format
Labels: fixing

#1106 Fix error in SortingRendererClass::Deinit
  src/w3d/renderer/sortingrenderer.cpp
Labels: bug, fixing

#1110 Fix error in AudioManager::Lose_Focus
  src/game/common/audio/audiomanager.cpp
Labels: bug, fixing

#1107 Fix error in SceneClass::Render
  src/w3d/renderer/scene.cpp
Labels: bug, fixing

#1108 Fix error in GameLODManager::Find_Static_LOD_Level
  src/game/common/gamelod.cpp
Labels: bug, fixing

#1114 Fix errors in operator<, operator> of Utf8String, Utf16String
  src/game/common/system/asciistring.h
  src/game/common/system/unicodestring.h
Labels: bug, fixing

#1119 Revert "Remove always.h from hot include files to reduce compile time"
  deps/baseconfig/src/unichar.h
  src/game/common/bitflags.h
  src/game/common/system/asciistring.h
  src/game/common/system/unicodestring.h
Labels: fixing

#1105 Fix error in SysTimeClass::Get
  src/w3d/lib/systimer.cpp
Labels: bug, fixing

#1111 Fix errors in AABoxIntersectionTestClass::Cull
  src/w3d/renderer/inttest.h
Labels: vanilla-bug, fixing
