Repository TheAssemblyArmada/Thyme, pull requests merged in 2024-08, with the labels that each got.

#1139 Fix debug compile error
  src/game/client/w3dassetmanager.cpp
  src/w3d/renderer/assetmgr.cpp
Labels: bug, fixing

#1141 Fix operator precedence in DDSFileClass::Merge_Color
  src/w3d/renderer/ddsfile.h
Labels: refactoring

#1143 Fix dds file buffer overrun
  src/w3d/renderer/ddsfile.cpp
Labels: bug, fixing

#1142 Fix w3dview camera movement
  src/tools/w3dviewer/graphicview.cpp
Labels: bug, fixing

#1144 Fix UI tooltips
  src/game/client/gui/gamewindow.cpp
  src/game/client/gui/gamewindowmanager.cpp
Labels: bug, fixing

#1146 Fix potential double free in HLodClass::Free
  src/w3d/renderer/hlod.cpp
Labels: bug
